### ISSUE TITLE
Authenticating to HackTheBox failed - error 422

### ISSUE THREAD

**Issue by Kobra3390** [Tut-k0/htb-academy-to-md#6]
while running the script I get this error (I don't have 2fa or strange passwords, everything worked before, I think htb has changed something):

```shell
Authenticating with HackTheBox...
Authenticating to HackTheBox failed.
Unexpected status code: 422
Response body: {"message":"The g-recaptcha-response field is required.","errors":{"g-recaptcha-response":["The g-recaptcha-response field is required."]}}
```

**Comment by Tut-k0** [comment]
Hey! Thank you for reporting this issue. It looks like HTB has implemented recaptcha for the login process. This will probably cause some pain in trying to automate the login for the platform.

Unfortunately I don't have a whole lot of time this weekend to dig into it. I will try to get a workaround implemented for now as soon as I can.

**Comment by Kobra3390** [comment]
great work man

Il giorno ven 19 lug 2024 alle ore 21:04 David Chandler <
***@***.***> ha scritto:
