### ISSUE TITLE
Error downloading/running script

### ISSUE THREAD

**Issue by Ghaithdev** [Tut-k0/htb-academy-to-md#8]
A number of LInux devices (Ubuntu, Pop_OS & Kali) have all run into a similar error. The long and short of it is that I run the installation commands as stated on the main page but then when trying to run the command cannot be found:
┌──(smeod㉿kali)-[~/Documents/htb-academy-to-md/src]
└─$ go build -o htb-academy-to-md
go: downloading golang.org/x/net v0.8.0
go: downloading github.com/JohannesKaufmann/html-to-markdown v1.3.7
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/PuerkitoBio/goquery v1.8.1
go: downloading github.com/andybalholm/cascadia v1.3.1
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
                                                                              
┌──(smeod㉿kali)-[~/Documents/htb-academy-to-md/src]
└─$ go build -buildvcs=false  -o htb-academy-to-md
htb-academy-md/src: go build htb-academy-md/src: copying /tmp/go-build3390951109/b001/exe/a.out: open htb-academy-to-md: permission denied
                                                                              
┌──(smeod㉿kali)-[~/Documents/htb-academy-to-md/src]
└─$ go build -o htb-academy-to-md                 
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
                                                                              
┌──(smeod㉿kali)-[~/Documents/htb-academy-to-md/src]
└─$ htb-academy-to-md -h             
htb-academy-to-md: command not found

**Comment by Tut-k0** [comment]
@Ghaithdev Your command output indicates that the `smeod` user does not own the files and directory for this repository on your local machine. Ensure that the repository files are owned by `smeod` before using `go build`, or alternatively build the program using `sudo`. If you cloned the repo with `sudo git clone`, then the files and directories will be owned by root by default.

**Comment by Ghaithdev** [comment]
Ah thank you, sorry about that I am a bit of a noob
