### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by Zapalouni** [Tut-k0/htb-academy-to-md#9]
Running this give me an error and that's the intro module. 
running kali : Linux *** 6.11.2-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15) x86_64 GNU/Linux
./htb-academy-md-linux -c "REDACTED" -m "https://academy.hackthebox.com/module/15/section/32"
Authenticating with HackTheBox...
Downloading requested module...
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
main.getModulePages({0xc000496000, 0x29b6}, {0x7ffc89545510, 0x33})
	/home/tut/Programming/go/htb-academy-md/src/export.go:283 +0x168
main.getModule({0x7ffc89545510, 0x33}, 0xc0000a7800)
	/home/tut/Programming/go/htb-academy-md/src/export.go:208 +0x106
main.main()
	/home/tut/Programming/go/htb-academy-md/src/main.go:17 +0x14b

**Comment by Tut-k0** [comment]
Hi @Zapalouni , I would try again using only the `htb_academy_session` cookie and see if that works for you. I don't have the same issue when fetching this module and it most likely a session or cookie issue.

**Comment by Tut-k0** [comment]
I'm going to go ahead and close this issue out, feel free to re-open this if the error occurs again after using valid cookies.
